export const SET_INVENTORY_TABLE = "SET_INVENTORY_TABLE";
export const GET_INVENTORY_DEPARTMENT = "GET_INVENTORY_DEPARTMENT";
export const GET_NON_INVENTORY = "GET_NON_INVENTORY";
export const SET_OFFICE = "SET_OFFICE";
export const SET_SECTIONS = "SET_SECTIONS";
export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const SET_OPEN_QTYMODAL = "SET_OPEN_QTYMODAL";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const SET_REQ_DTLS = "SET_REQ_DTLS";
export const SET_REQ_FOOTER = "SET_REQ_FOOTER";
export const SET_REQ_HEADER = "SET_REQ_HEADER";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const GET_REQUEST_INFO = "GET_REQUEST_INFO";
export const GET_SINGLEREQUEST_HEADER = "GET_SINGLEREQUEST_HEADER";
export const GET_SINGLEREQUEST_DETAILS = "GET_SINGLEREQUEST_DETAILS";

export const SET_INVENTORY_TABLE_BYSTATUS = "SET_INVENTORY_TABLE_BYSTATUS";
export const GET_DASHBOARD_NUMBERS = "GET_DASHBOARD_NUMBERS";
export const SET_STATUS_FOR_TABLE = "SET_STATUS_FOR_TABLE";
export const SET_SEARCH_FOR_TABLE = "SET_SEARCH_FOR_TABLE";

export const SET_INVENTORY_ITEM_ACTIVE = "SET_INVENTORY_ITEM_ACTIVE";
export const SET_INVENTORY_SEARCH_ITEM = "SET_INVENTORY_SEARCH_ITEM";
export const SET_BASE64TO_PDF = "SET_BASE64TO_PDF";
export const SET_BACKDROP_OPEN = "SET_BACKDROP_OPEN";
export const SET_OPEN_ADDITEMMODAL = "SET_OPEN_ADDITEMMODAL";
export const SET_OPEN_SUPPLIER_MODAL = "SET_OPEN_SUPPLIER_MODAL";
export const SET_ADD_NEW_ITEM = "SET_ADD_NEW_ITEM";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const SET_SELECTED_SUPPLIERS = "SET_SELECTED_SUPPLIERS";
export const GET_SELECTED_SUPPLIERS = "GET_SELECTED_SUPPLIERS";
export const GET_SELECTED_SUPPLIERS_ITEMS = "GET_SELECTED_SUPPLIERS_ITEMS";
export const SET_OPEN_ITEM_FOR_SUPPLIER_MODAL = "SET_OPEN_ITEM_FOR_SUPPLIER_MODAL";

